sudo: false
language: node_js
node_js:
  - 7.0.0
install:
  - npm install
cache:
  directories:
    - ./node_modules
before_script:
  - npm link
script:
  - gon -v
  - gon create demo
  - cd demo
  - gon dev &
  - pid=$!
  - sleep 40
  - phantomjs ./test/phantom.js
  - kill $pid
  - gon release
