sudo: false
language: node_js
node_js:
  - 7.6.0
install:
  - npm install
cache:
  directories:
    - ./node_modules
before_script:
  - npm link
  - ./node_modules/.bin/gulp --gulpfile ./gulpfile.babel.js eslint
script:
  - gon -v
  - gon create demo
  - cd demo
  - gon dev 9000 &
  - pid=$!
  - sleep 40
  - phantomjs ../test/phantom.js
  - kill $pid
  - gon release
